import type { Metadata } from "next";
import "./globals.css";
import { Header } from "src/common/Header";
import { Sidebar } from "src/common/Sidebar";
import { Logo } from "src/assets/icons";

export const metadata: Metadata = {
  title: "Next Vote 20th",
  description: "Generated by Onedwo Punch",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="no-scrollbar">
      <body>
        <Logo />
        <Header />
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
