import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next Vote 20th",
  description: "Generated by Onedwo Punch",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
